### ISSUE TITLE
putStringArray can fail and that case is not handled

### ISSUE THREAD

**Issue by brettle** [DeepBlueRobotics/RobotCode2018#16]
https://github.com/DeepBlueRobotics/RobotCode2018/blob/2ac79eb04c867c5054e83b0cd1b503993213dbec/Robot2018/src/tests/scriptupload/scriptupload.py#L27

**Comment by brettle** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [putStringArray can fail and that case is not handled #16](https://trello.com/c/CcjcIjK3/139-putstringarray-can-fail-and-that-case-is-not-handled-16)

**Comment by MysteryPig** [comment]
I don't think we can handle this—as far as I could tell, it doesn't throw anything upon failure.

**Comment by MysteryPig** [comment]
Wait, it's supposed to upload it as one string. When did it get changed?

**Comment by kevinzwang** [comment]
One way to do it is to get from nt and then compare it to the data you put in

**Comment by brettle** [comment]
Yes, also check the docs for what putStringArray() returns.

**Comment by brettle** [comment]
This was fixed.
