### ISSUE TITLE
Rename getGyro() to getGyroAngle()

### ISSUE THREAD

**Issue by brettle** [DeepBlueRobotics/RobotCode2018#27]
https://github.com/DeepBlueRobotics/RobotCode2018/blob/532bc103c3b1446a6e62ee9c14928650ede07a49/Robot2018/src/org/usfirst/frc/team199/Robot2018/subsystems/Drivetrain.java#L199

**Comment by brettle** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Rename getGyro() to getGyroAngle()](https://trello.com/c/XqiYgIOU/150-rename-getgyro-to-getgyroangle)

**Comment by doawelul** [comment]
Resolved in newest pr
