### ISSUE TITLE
Add velocity PIDControllers for left and right side of drivetrain to Drivetrain class

### ISSUE THREAD

**Issue by brettle** [DeepBlueRobotics/RobotCode2018#28]
The Drivetrain subsystem should be responsible for moving the left and right side of the drivetrain at requested speeds. That implies adding velocity PID controllers for each side and using those controllers as SpeedControllers passed to DifferentialDrive. To that end, the velocity PID controllers should implement both PIDControllerInterface (so that they can be tuned and monitored) and SpeedController (so that they can be passed to the DifferentialDrive constructor). Two implementations should be developed -- one which uses wpilib's PIDController to do the control and the other which uses the TalonSRX's internal PID features.

**Comment by brettle** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add velocity PIDControllers for left and right side of drivetrain to Drivetrain class](https://trello.com/c/hFrV9QGa/152-add-velocity-pidcontrollers-for-left-and-right-side-of-drivetrain-to-drivetrain-class)

**Comment by doawelul** [comment]
Split moveController to each side of the drivetrain
