### ISSUE TITLE
Make ShiftDriveType an InstantCommand so that it doesn't execute unnecessarily many times

### ISSUE THREAD

**Issue by brettle** [DeepBlueRobotics/RobotCode2018#30]
https://github.com/DeepBlueRobotics/RobotCode2018/blob/532bc103c3b1446a6e62ee9c14928650ede07a49/Robot2018/src/org/usfirst/frc/team199/Robot2018/commands/ShiftDriveType.java#L12

**Comment by brettle** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Make ShiftDriveType an InstantCommand so that it doesn't execute unnecessarily many times](https://trello.com/c/5Hm8RhlK/154-make-shiftdrivetype-an-instantcommand-so-that-it-doesnt-execute-unnecessarily-many-times)

**Comment by doawelul** [comment]
Changed in latest pull request.
