### ISSUE TITLE
Make ShiftHighGear, ShiftLowGear, and ShiftNeutral InstantCommands

### ISSUE THREAD

**Issue by brettle** [DeepBlueRobotics/RobotCode2018#31]
https://github.com/DeepBlueRobotics/RobotCode2018/blob/532bc103c3b1446a6e62ee9c14928650ede07a49/Robot2018/src/org/usfirst/frc/team199/Robot2018/commands/ShiftHighGear.java#L12

These should not need to keep setting the solenoid value for any period of time. If they do, it's probably a symptom that something else is wrong and should be fixed.

**Comment by brettle** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Make ShiftHighGear, ShiftLowGear, and ShiftNeutral InstantCommands](https://trello.com/c/54VY8hU9/155-make-shifthighgear-shiftlowgear-and-shiftneutral-instantcommands)

**Comment by doawelul** [comment]
I agree that the solenoid only needs to be set once (theoretically), however, after a short but non-negligible amount of time, we need to set it back to neutral. We will need testing to see if adding shift to forward/backwards then shifting to neutral gives enough time for the mechanism to actually deploy.
