### ISSUE TITLE
Coordinate parsing should allow spaces inside parentheses

### ISSUE THREAD

**Issue by brettle** [DeepBlueRobotics/RobotCode2018#44]
The output should not be empty in test11():

https://github.com/DeepBlueRobotics/RobotCode2018/blob/089009aa77fac0f6822741510807346546a06e0b/Robot2018/test/org/usfirst/frc/team199/Robot2018/ParseScriptFileTest.java#L150

Ditto for test13().

Most importantly, `"(4, 20)"` should be allowed since putting a space after a comma in a common convention and would be a particularly common mistake.

**Comment by brettle** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Coordinate parsing should allow spaces inside parentheses](https://trello.com/c/7GFaz9YK/168-coordinate-parsing-should-allow-spaces-inside-parentheses)

**Comment by kevinzwang** [comment]
This is a significantly harder thing to do, since you can't just `string.split(" ")`. I'll implement it later, but it isn't priority for now.

**Comment by brettle** [comment]
I'm pretty sure this is a one line fix that doesn't involve a call to
split().

On Jan 29, 2018 1:55 PM, "Kevin Wang" <notifications@github.com> wrote:

This is a significantly harder thing to do, since you can't just string.split("
"). I'll implement it later, but it isn't priority for now.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/DeepBlueRobotics/RobotCode2018/issues/44#issuecomment-361399903>,
or mute the thread
