### ISSUE TITLE
Parsing errors should be logged as errors instead of warnings and tests should verify that such logging is occuring

### ISSUE THREAD

**Issue by brettle** [DeepBlueRobotics/RobotCode2018#45]
If the script can't be parsed, something is wrong and the user needs to take action to correct the problem. As a result, this condition should be logged as an error instead of a warning.

The tests should also verify that the appropriate logging occurs. It's not critical that the tests verify the full text of the error message, but they should verify that the message is logged as an error instead of a warning.

**Comment by brettle** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Parsing errors should be logged as errors instead of warnings and tests should verify that such logging is occuring](https://trello.com/c/jQnDSxyG/169-parsing-errors-should-be-logged-as-errors-instead-of-warnings-and-tests-should-verify-that-such-logging-is-occuring)

**Comment by kevinzwang** [comment]
So the logs are System.err.println(), they just are labeled as warnings. Should I just change it from `"[WARNING]"` to `"[ERROR]"`?

**Comment by brettle** [comment]
Yes.

--Dean

**Comment by kevinzwang** [comment]
#62
