### ISSUE TITLE
implement current limit on motors (so don't exceed breaker ratings)

### ISSUE THREAD

**Issue by lhmcgann** [DeepBlueRobotics/RobotCode2018#47]
https://trello.com/c/zTvvaVgv/172-implement-current-limit-on-dt-motors-so-doesnt-exceed-40amps

**Comment by lhmcgann** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [implement current limit on DT motors (so doesn't exceed 40Amps)](https://trello.com/c/zTvvaVgv/172-implement-current-limit-on-dt-motors-so-doesnt-exceed-40amps)

**Comment by brettle** [comment]
Not limited to drivetrain motors. This is a good practice for all motors. It can be implemented using either the current limiting feature of the talons or by monitoring the current pulled through the associated PDP channel.
