### ISSUE TITLE
set the tolerances for the velocity PID controllers

### ISSUE THREAD

**Issue by lhmcgann** [DeepBlueRobotics/RobotCode2018#48]
https://trello.com/c/CpbgyDUk/173-add-a-dead-zone-ie-threshold-to-joysticks-so-the-velocity-pid-doesnt-go-crazy

**Comment by lhmcgann** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [add a "dead zone" (i.e. threshold) to joysticks so the velocity PID doesn't go crazy](https://trello.com/c/CpbgyDUk/173-add-a-dead-zone-ie-threshold-to-joysticks-so-the-velocity-pid-doesnt-go-crazy)

**Comment by brettle** [comment]
It might be better to set the tolerance on the velocity pid controller to ensure that differences on the order of joystick jitter do not cause the controller to think it has not reached its target.
