### ISSUE TITLE
PIDMove and PIDTurn should not finish until movement stops

### ISSUE THREAD

**Issue by brettle** [DeepBlueRobotics/RobotCode2018#63]
At the moment, these commands finish if onTarget() is true for just one cycle. However, this can happen while passing through the target value (i.e. overshooting). The result is that PID is disabled while still in motion and the final resting position/orientation can be significantly different that requested.

@Gabe-Mitnick suggests only letting isFinished() return true if we are onTarget() and the rate (e.g. ahrs.getRate() or encoder.getRate()) are sufficiently small.

**Comment by brettle** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [PIDMove and PIDTurn should not finish until movement stops](https://trello.com/c/ZVffFgbP/200-pidmove-and-pidturn-should-not-finish-until-movement-stops)

**Comment by doawelul** [comment]
Done in latest commit.

**Comment by brettle** [comment]
Fixed by 305b8e300c2088afe81d29d72316e05dc5348bc9.
