### ISSUE TITLE
new feature request: slow mode on trigger hold

### ISSUE THREAD

**Issue by Gabe-Mitnick** [DeepBlueRobotics/RobotCode2018#89]
rafi and maya (as drivers, although idk if they're the actual drivers) have a feature request. the robot should move slower while they hold the triggers. preferably, forward-and-back movement would be slower while holding the trigger on the forward-and-back arcade joystick, and turning would be slower while the trigger on that joystick is held. this would probably be a coefficient of maybe .5, probably changable on shuffleboard so they can try different things, that gets turned on on trigger down and turned off on trigger up.

**Comment by Gabe-Mitnick** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [new feature: slow mode on trigger hold](https://trello.com/c/EuqOe9fQ/236-new-feature-slow-mode-on-trigger-hold)

**Comment by doawelul** [comment]
Done, put in pull request.
